import type { Metadata } from "next";

import { cn } from "@/helpers/cn";
import { roboto } from '@/helpers/fonts';

import { Navbar } from "@/components";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={roboto.variable}>
      <body className={cn("antialiased bg-slate-800 text-slate-300", ``)}>
        <Navbar />
        <div className="ml-72">
          {children}
        </div>
      </body>
    </html>
  );
}
